In [1]:
import pandas as pd

In [2]:
# Load the URL for world population on wikipedia
url = "https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population"
tables=pd.read_html(url)
#check how many tables were found
print(f"Number of tables found: {len(tables)}")
# Display the first table
print(tables[0].head())

Number of tables found: 3
        Location  Population % of world         Date  \
0          World  8232000000       100%  13 Jun 2025
1          India  1413324000      17.3%   1 Mar 2025
2          China  1408280000      17.2%  31 Dec 2024
3  United States   340110988       4.2%   1 Jul 2024
4      Indonesia   282477584       3.5%  30 Jun 2024

  Source (official or from the United Nations) Notes
0                          UN projection[1][3]   NaN
1                       Official projection[4]   [b]
2                         Official estimate[5]   [c]
3                         Official estimate[6]   [d]
4                National annual projection[7]   NaN

In [3]:
#show all tables
for i, table in enumerate(tables):
    print(f"Table {i}:")
    print(table.head(), "\n")

Table 0:
        Location  Population % of world         Date  \
0          World  8232000000       100%  13 Jun 2025
1          India  1413324000      17.3%   1 Mar 2025
2          China  1408280000      17.2%  31 Dec 2024
3  United States   340110988       4.2%   1 Jul 2024
4      Indonesia   282477584       3.5%  30 Jun 2024

  Source (official or from the United Nations) Notes
0                          UN projection[1][3]   NaN
1                       Official projection[4]   [b]
2                         Official estimate[5]   [c]
3                         Official estimate[6]   [d]
4                National annual projection[7]   NaN

Table 1:
  vteLists of countries by population statistics  \
0                                         Global
1                          Continents/subregions
2                               Intercontinental
3                             Cities/urban areas
4                                Past and future

    vteLists of countries by population statistics.1
0  Current population United Nations Demographics...
1  Africa Antarctica Asia Europe North America Ca...
2  Americas Arab world Commonwealth of Nations Eu...
3  World cities National capitals Megacities Mega...
4  Past and future population Estimates of histor...

Table 2:
                                            vteWorld  \
0  AfghanistanAlbaniaAlgeriaAndorraAngolaAntigua ...

                                          vteWorld.1
0  AfghanistanAlbaniaAlgeriaAndorraAngolaAntigua ...

In [4]:
# step 1: Import the required libraries
import pandas as pd

# step 2: Load the URL
url = 'https://www.worldometers.info/world-population/population-by-country/'

# step 3: Fetch the HTML content with headers and read the HTML table into a DataFrame
import requests
# headers to avoid being blocked
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}
# headers are important to avoid being blocked by the server
response = requests.get(url, headers=headers)
response.raise_for_status()  # Raise an error for bad status codes

tables = pd.read_html(response.text)

# step 4: Check the number of tables
print(f"Number of tables found: {len(tables)}")
# step 5: Display the first few rows of the first table
tables[0].head()

C:\Users\ahmad\AppData\Local\Temp\ipykernel_19200\62090676.py:15: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(response.text)

Number of tables found: 1

,#,Country (or dependency),Population (2025),Yearly Change,Net Change,Density (P/Km²),Land Area (Km²),Migrants (net),Fert. Rate,Median Age,Urban Pop %,World Share
0,1,India,1463865525,0.89%,12929734,492,2973190,"−495,753",1.94,28.8,37.1%,17.78%
1,2,China,1416096094,−0.23%,"−3,225,184",151,9388211,"−268,126",1.02,40.1,67.5%,17.20%
2,3,United States,347275807,0.54%,1849236,38,9147420,1230663,1.62,38.5,82.8%,4.22%
3,4,Indonesia,285721236,0.79%,2233305,158,1811570,"−39,509",2.10,30.4,59.6%,3.47%
4,5,Pakistan,255219554,1.57%,3950390,331,770880,"−1,235,336",3.50,20.6,34.4%,3.10%

In [5]:
# Save the first table to a CSV file
tables[0].to_csv('world_population_by_country.csv', index=False)